-- MySQL Script generated by MySQL Workbench
-- Sat May 26 15:42:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `idpais` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipo` (
  `idequipo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `pais_idpais` INT NOT NULL,
  `equipocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idequipo`),
  INDEX `fk_equipo_pais_idx` (`pais_idpais` ASC),
  CONSTRAINT `fk_equipo_pais`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partidos` (
  `idpartidos` INT NOT NULL,
  PRIMARY KEY (`idpartidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `ideventos` INT NOT NULL,
  `puntajeTotal` INT NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_cierre` DATETIME NULL,
  `equipo_idequipo` INT NOT NULL,
  PRIMARY KEY (`ideventos`),
  INDEX `fk_eventos_equipo1_idx` (`equipo_idequipo` ASC),
  CONSTRAINT `fk_eventos_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `mydb`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videos` (
  `idvideos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `videoscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idvideos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `idpais` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `usuariocol` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `pais_idpais` INT NOT NULL,
  `monedas` INT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_pais1_idx` (`pais_idpais` ASC),
  CONSTRAINT `fk_usuario_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sala` (
  `idsala` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `cantidad_participantes` INT NULL,
  `monto_total` DOUBLE NULL,
  `tipo` VARCHAR(45) NULL,
  `limite_participantes` VARCHAR(45) NULL,
  `apuesta_base` VARCHAR(45) NULL,
  PRIMARY KEY (`idsala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partido` (
  `idpartido` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `equipo1` VARCHAR(45) NULL,
  `equipo2` VARCHAR(45) NULL,
  `partidoscol` VARCHAR(45) NULL,
  `goles_equipo1` VARCHAR(45) NULL,
  `goles_equipo2` VARCHAR(45) NULL,
  PRIMARY KEY (`idpartido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imagenes` (
  `idimagenes` INT NOT NULL,
  `imagenescol` VARCHAR(100) NULL,
  `object` VARCHAR(50) NULL,
  `id` INT NULL,
  PRIMARY KEY (`idimagenes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentario` (
  `idcomentario` INT NOT NULL,
  `comentario` VARCHAR(250) NULL,
  `usuario_idusuario` INT NOT NULL,
  `sala_idsala` INT NOT NULL,
  PRIMARY KEY (`idcomentario`, `usuario_idusuario`, `sala_idsala`),
  INDEX `fk_comentarios_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_comentarios_sala1_idx` (`sala_idsala` ASC),
  CONSTRAINT `fk_comentarios_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_sala1`
    FOREIGN KEY (`sala_idsala`)
    REFERENCES `mydb`.`sala` (`idsala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuenta` (
  `idcuenta` INT NOT NULL,
  `numero_tarjeta` VARCHAR(45) NULL,
  `caducidad` DATETIME NULL,
  `Direccion` VARCHAR(100) NULL,
  `codigo_seguridad` VARCHAR(50) NULL,
  `ciudad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`idcuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`noticias` (
  `idnoticias` INT NOT NULL,
  `tema` VARCHAR(45) NULL,
  PRIMARY KEY (`idnoticias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_sala` (
  `iddetalle_sala` INT NOT NULL,
  `sala_idsala` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`iddetalle_sala`, `sala_idsala`, `usuario_idusuario`),
  INDEX `fk_detalle_sala_sala1_idx` (`sala_idsala` ASC),
  INDEX `fk_detalle_sala_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_detalle_sala_sala1`
    FOREIGN KEY (`sala_idsala`)
    REFERENCES `mydb`.`sala` (`idsala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_sala_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
